#ifndef _CONST_H_

#define _CONST_H_

#define TAG_MAVERICK 1
#define MAVERICK_CATEGORY_BITMASK					0x01
#define MAVERICK_COLLISION_AND_CONTACT_TEST_BITMASK 0x02


#define LINE_CATEGORY_BITMASK 0x01
#define LINE_COLISION_AND_CONTACT_TEST_BITMASK 0x02

#define ENEMY_CATEGORY_BITMASK					0x02
#define ENEMY_COLLISION_AND_CONTACT_TEST_BITMASK 0x01

#define TAG_WALL 2
#define WALL_CATEGORY_BITMASK 0x03
#define WALL_COLLISION_AND_CONTACT_TEST_BIT_MASK 0xFFFF



#define TAG_EHIT 7
#define TAG_DOG 3
#define TAG_BANDIT 4
#define TAG_BOSS 5
#define TAG_HIT 6

#endif // !_CONST_H_
