#ifndef _CONST_H_

#define _CONST_H_

#define TAG_MAVERICK 1
#define MAVERICK_CATEGORY_BITMASK					0x01
#define MAVERICK_COLLISION_AND_CONTACT_TEST_BITMASK 0x02

#define ENEMY_CATEGORY_BITMASK					0x02
#define ENEMY_COLLISION_AND_CONTACT_TEST_BITMASK 0x01

#define TAG_WALL 2
#define WALL_CATEGORY_BITMASK 0x03
#define WALL_COLLISION_AND_CONTACT_TEST_BIT_MASK 0xFFFF
#endif // !_CONST_H_
