#ifndef _CONST_H_

#define _CONST_H_
#define TAG_MAVERICK 1
#define MAVERICK_CATEGORY_BITMASK					1
#define MAVERICK_COLLISION_AND_CONTACT_TEST_BITMASK 2
#define ENEMY_CATEGORY_BITMASK					0x02
#define ENEMY_COLLISION_AND_CONTACT_TEST_BITMASK 0x01
#endif // !_CONST_H_
